import type { AgentState, AnswerPage, AnswerPageDeliveryFacts, AnswerPageReservationOutcome, Binding, BindingMetadataPatch, BindingTitleProjectionInput, BindingTitleProjectionResult, CardInteraction, CardInteractionActionKind, DeadLetterActionOutcome, DeliveryFailureMetadata, DurablePromptWorkScan, ExternalTurnAdoption, ExternalTurnSupersessionFence, FailureSummary, HerdrAgentSession, HerdrPane, HerdrPaneCreationOptions, IncomingLarkCardAction, IncomingLarkMessage, InstanceLease, LarkCardActionResult, MainCardReservationOutcome, OperationalSummary, OrphanBindingProjectionInput, OrphanBindingProjectionResult, OutboundFailureTransition, OutboundReply, OutboxDispatcherDiagnostics, PaneCloseOperation, PaneControlOperation, PaneControlOperationKind, ProjectSelection, ProjectSelectionClaim, PromptJob, RecoverOrphanBindingProjectionInput, RecoverOrphanBindingProjectionResult, RetiredPaneCleanupOperation, RuntimeDegradationInput, RuntimeDegradationResult, RuntimeObservation, RuntimeObservationApplication, RuntimeTurnObservation, SessionOperation, SessionOperationKind, SessionOperationState, SessionSummary, SqliteIntegrityInspection, StaleOutboxQuarantineRecovery, TranscriptTurnClaimOutcome } from "./types.js";
import type { SteerReceipt } from "./agent-runtime.js";
import type { TopicViewState } from "./topic-view.js";
import type { RunCardView, RunProgressEvent } from "./run-card-view.js";
import type { SessionTransition } from "./pane-thread-lifecycle.js";
import type { BridgeEvent } from "./events.js";
import type { PaneControlOutcome } from "./pane-control-lifecycle.js";
import type { AgentInstance, CreateAgentInstanceInput, InstanceProvisioningCheckpoint, InstanceRemovalPlan, WorkspaceLease, WorkspaceLeaseState } from "./agent-instance.js";
import type { ControlActor } from "./commands.js";
import type { InstanceEvent, InstanceEventKind, InstanceOperation, InstanceTurn, InstanceTurnCursor, InstanceTurnPage, InstanceTurnState, InstanceTurnSummary } from "./instance-turn.js";
import type { ApprovalGrant, ApprovalIdentity, ApprovalRequest } from "./approval-policy.js";
import type { WorkerTurnCardChange, WorkerTurnCardPage, WorkerTurnCardView } from "./worker-turn-card-view.js";
import type { AcceptTurnControlOperationInput, TurnControlOperation, TurnControlState } from "./turn-control.js";
import type { HerdrPort, LarkPort, TraexTranscriptCursorPort, TraexTranscriptMainStatus, TraexTranscriptObservation, TraexTranscriptOpenResult, TraexTranscriptPlanStep, TraexTranscriptReaderPort, TraexTranscriptUnavailableReason } from "./ports/external.js";
import type { AcceptInstanceTurnWithCardInput, InstanceStore } from "./ports/instance.js";
import type { TurnControlStore } from "./ports/turn-control.js";
import type { ClaimedPrompt, PromptAcceptanceStore, PromptRunStore } from "./ports/prompt.js";
import type { ModelPreference } from "./model-selection.js";
import type { AnswerPageStore, MainCardStore, ProjectionStore, QueueFeedbackStore, WorkerTurnCardStore } from "./ports/projection.js";
import type { BindingProvisioningStore, RetiredPaneCleanupStore, RuntimeReconciliationStore } from "./ports/binding.js";
import type { PaneCloseStore, PaneControlStore } from "./ports/pane-operations.js";
import type { ImmediateOutboundDispatcher, OutboundCheckpointSubscriber, OutboundIntentPort, OutboundIntentStore, OutboxDispatcherControl, OutboxStore } from "./ports/outbox.js";
import type { DatabaseIntegrityStore, HealthStore, LeaseStore } from "./ports/health.js";
import type { CardInteractionStore, DeliveryRecoveryStore, ExternalTurnObservationStore, InboundRoutingStore, ModelSelectionStore, OperationsQueryStore, PaneRetentionStore, SessionAdministrationStore, SessionOperationStore } from "./ports/workflow.js";
import type { CommandIntentStore } from "./ports/swarm-command.js";
export type { HerdrPort, LarkPort, TraexTranscriptCursorPort, TraexTranscriptMainStatus, TraexTranscriptObservation, TraexTranscriptOpenResult, TraexTranscriptPlanStep, TraexTranscriptReaderPort, TraexTranscriptUnavailableReason, AcceptInstanceTurnWithCardInput, InstanceStore, TurnControlStore, ClaimedPrompt, PromptAcceptanceStore, PromptRunStore, AnswerPageStore, MainCardStore, ProjectionStore, QueueFeedbackStore, WorkerTurnCardStore, BindingProvisioningStore, RetiredPaneCleanupStore, RuntimeReconciliationStore, PaneCloseStore, PaneControlStore, ImmediateOutboundDispatcher, OutboundCheckpointSubscriber, OutboundIntentPort, OutboundIntentStore, OutboxDispatcherControl, OutboxStore, DatabaseIntegrityStore, HealthStore, LeaseStore, CardInteractionStore, DeliveryRecoveryStore, ExternalTurnObservationStore, InboundRoutingStore, ModelSelectionStore, ModelPreference, OperationsQueryStore, PaneRetentionStore, SessionAdministrationStore, SessionOperationStore, CommandIntentStore };



export interface ClassifiedPromptInput {
  prompt: Omit<PromptJob, "state" | "observationState" | "attemptCount" | "error" | "createdAt" | "updatedAt" | "dispatchKind" | "parentPromptId" | "steeringOrigin" | "sourcePromptId" | "wasDetached" | "dispatchedAt" | "transcriptTurnId" | "transcriptTurnStartedAt" | "executionOrigin">;
  ordinaryView: RunCardView;
  steeringView: RunCardView;
  rootMessageId: string;
  maxQueueDepth: number;
  expectedBindingGeneration: number;
  candidateParentPromptId: string | null;
  activeAfter: string;
  acceptedAt: string;
  answerCardFor(view: RunCardView): object;
}

type ClassifiedPromptFallbackReason = "no_candidate" | "binding_changed" | "parent_inactive" | "parent_detached" | "parent_state" | "parent_stale" | null;

export type ClassifiedPromptAcceptance = {
  prompt: PromptJob;
  view: RunCardView;
  inserted: boolean;
  decision: "automatic_steering" | "ordinary";
  fallbackReason: ClassifiedPromptFallbackReason;
} | {
  inserted: false;
  decision: "queue_full";
  fallbackReason: ClassifiedPromptFallbackReason;
};

export interface BindingStorePort {
  close(): void;
  activateWriteFence(ownerId: string, fencingToken: number): void;
  deactivateWriteFence(): void;
  acquireInstanceLease(ownerId: string, now: string, expiresAt: string): InstanceLease | null;
  renewInstanceLease(ownerId: string, fencingToken: number, now: string, expiresAt: string): InstanceLease | null;
  releaseInstanceLease(ownerId: string, fencingToken: number): boolean;
  recordInboundMessage(message: IncomingLarkMessage): boolean;
  claimNextInboundMessage(): IncomingLarkMessage | null;
  markInboundMessageAccepted(eventId: string): void;
  releaseInboundMessage(eventId: string, error: string): void;
  recoverProcessingInboundMessages(): number;
  isBridgeMessage(messageId: string): boolean;
  recordBridgeMessage(messageId: string): void;
  createPendingBinding(input: {
    id: string;
    projectId?: string | null;
    workspaceId: string;
    chatId: string;
    topicId: string | null;
    rootMessageId: string | null;
    title: string;
    creatorOpenId?: string | null;
  }): Binding;
  createCardInteraction(input: { id: string; bindingId: string; bindingGeneration: number; actorOpenId: string; actionKind: CardInteractionActionKind; parentPromptId: string | null; targetPromptId: string | null; expiresAt: string }): CardInteraction;
  getCardInteraction(id: string): CardInteraction | null;
  consumeCardInteraction(input: { id: string; actorOpenId: string; bindingId: string; bindingGeneration: number; now: string; resultCode: string }): { outcome: "consumed" | "duplicate" | "missing" | "unauthorized" | "expired" | "stale"; interaction: CardInteraction | null };
  acceptSessionOperation(input: { id: string; idempotencyKey: string; interactionId: string; actorOpenId: string; bindingId: string; bindingGeneration: number; expectedPaneId: string | null; expectedTerminalId: string | null; kind: SessionOperationKind; argument: string | null; now: string }): { outcome: "accepted" | "duplicate" | "missing" | "unauthorized" | "expired" | "stale"; operation: SessionOperation | null };
  getSessionOperation(id: string): SessionOperation | null;
  claimNextSessionOperation(bindingId?: string): SessionOperation | null;
  finishSessionOperation(id: string, state: Extract<SessionOperationState, "succeeded" | "rejected" | "failed" | "uncertain">, detail?: string | null): SessionOperation | null;
  listRecoverableSessionOperations(): SessionOperation[];
  pruneTerminalSessionOperations(cutoff: string, limit: number): number;
  convertFailedSteeringToTurn(input: { interactionId: string; actorOpenId: string; bindingId: string; bindingGeneration: number; sourcePromptId: string; newPromptId: string; newLarkMessageId: string; now: string; view: RunCardView; rootMessageId: string; answerCardFor(view: RunCardView): object }): { outcome: "converted" | "duplicate" | "missing" | "unauthorized" | "stale"; prompt: PromptJob | null };
  createResetCandidate(input: { oldBindingId: string; newBindingId: string; title: string; actorOpenId: string; resetMessageId: string }): { previous: Binding; replacement: Binding; created: boolean };
  cutoverResetCandidate(input: { oldBindingId: string; newBindingId: string; cleanupOperationId: string; actorOpenId: string; expectedCwd: string }): { previous: Binding; replacement: Binding; cleanup: RetiredPaneCleanupOperation; cancelledPromptIds: string[] };
  listRetiredPaneCleanupOperations(states?: readonly RetiredPaneCleanupOperation["state"][]): RetiredPaneCleanupOperation[];
  claimRetiredPaneCleanup(id: string): RetiredPaneCleanupOperation | null;
  updateRetiredPaneCleanup(id: string, state: RetiredPaneCleanupOperation["state"], detail?: string | null): RetiredPaneCleanupOperation | null;
  completeRetiredPaneCleanup(id: string): RetiredPaneCleanupOperation | null;
  createProjectSelection(input: { id: string; commandMessageId: string; chatId: string; topicId: string | null; rootMessageId: string; actorOpenId: string; requestedTitle: string | null; initialPromptText?: string | null; expiresAt: string; card: object }): ProjectSelection;
  getProjectSelection(id: string): ProjectSelection | null;
  claimProjectSelection(input: { selectionId: string; projectId: string; messageId: string; chatId: string; actorOpenId: string; allowedProjectIds: string[] }): ProjectSelectionClaim;
  recoverProcessingProjectSelections(): number;
  listProcessingProjectSelections(): ProjectSelection[];
  listCompletedProjectSelectionsWithInitialPrompt(): ProjectSelection[];
  linkProjectSelectionBinding(id: string, bindingId: string): ProjectSelection;
  pauseProjectSelection(id: string, error: string): ProjectSelection;
  completeProjectSelection(id: string, bindingId: string): ProjectSelection;
  failProjectSelection(id: string, error: string): ProjectSelection;
  createPaneCloseRequest(input: { id: string; bindingId: string; paneId: string; actorOpenId: string; codeHash: string; expiresAt: string }): void;
  createAutomaticPaneCloseOperation(input: { id: string; bindingId: string; paneId: string; now: string }): void;
  consumePaneCloseRequest(input: { bindingId: string; paneId: string; actorOpenId: string; codeHash: string; now: string }):
    | { outcome: "consumed"; operationId: string; paneId: string }
    | { outcome: "invalid" | "unauthorized" | "expired" | "stale" };
  finishPaneCloseRequest(operationId: string, state: "succeeded" | "rejected" | "uncertain", detail?: string): void;
  listUnresolvedPaneCloseOperations(): PaneCloseOperation[];
  updateBindingMetadata(id: string, patch: BindingMetadataPatch): Binding;
  replaceProvisioningPane(input: { bindingId: string; expectedPaneId: string; expectedGeneration: number; pane: HerdrPane }): Binding;
  transitionBinding(id: string, transition: SessionTransition): Binding;
  applyRuntimeObservation(input: { bindingId: string; expectedPaneId: string; expectedGeneration: number; pane: HerdrPane }): RuntimeObservationApplication;
  reconcileBindingTitleWithProjection(input: BindingTitleProjectionInput): BindingTitleProjectionResult;
  degradeBindingWithProjection(input: RuntimeDegradationInput): RuntimeDegradationResult;
  orphanBindingWithProjection(input: OrphanBindingProjectionInput): OrphanBindingProjectionResult;
  recoverOrphanBindingWithProjection(input: RecoverOrphanBindingProjectionInput): RecoverOrphanBindingProjectionResult;
  transitionBindingWithOutbox(input: { id: string; transition: SessionTransition; event: BridgeEvent; view: TopicViewState; messageId: string; card: object }): Binding;
  attachBindingPane(id: string, pane: HerdrPane, replacement: boolean): Binding;
  hasBindingPrimaryToolCapability(bindingId: string, expectedGeneration: number): boolean;
  revokeBindingPrimaryToolCapability(bindingId: string, expectedGeneration: number): boolean;
  findBindingByTopic(topicId: string): Binding | null;
  findBindingByLarkScope(topicId: string | null, rootMessageId: string | null): Binding | null;
  findBindingByPane(paneId: string): Binding | null;
  getBinding(id: string): Binding | null;
  getPrompt(id: string): PromptJob | null;
  getActiveExternalPrompt(bindingId: string, expectedGeneration: number): PromptJob | null;
  listBindings(): Binding[];
  listBindingsByState(state: Binding["state"]): Binding[];
  listSessions(chatId: string): SessionSummary[];
  listFailures(chatId: string): FailureSummary[];
  countPendingPrompts(bindingId: string): number;
  listQueuedTurnPromptIds(bindingId: string): string[];
  listQueuedTurnRunCards(bindingId: string): RunCardView[];
  listCompletedOrdinaryTurnDurations(bindingId: string, limit: number): number[];
  loadQueueFeedbackInputs(bindingId: string): { activeStartedAt: string | null; queued: RunCardView[]; durationsMs: number[] };
  projectQueuedRunCards(input: {
    bindingId: string;
    projections: Array<{ expectedViewVersion: number; view: RunCardView; card: object | null }>;
  }): { projected: RunCardView[]; stalePromptIds: string[]; outboxReserved: boolean };
  acceptPaneControlOperation(input: { id: string; idempotencyKey: string; bindingId: string; paneId: string; terminalId: string | null; bindingGeneration: number; kind: PaneControlOperationKind; payload?: string | null; parentPromptId?: string | null; actorOpenId: string; sourceMessageId: string }): { operation: PaneControlOperation; inserted: boolean };
  claimNextPaneControlOperation(bindingId?: string): PaneControlOperation | null;
  claimPaneControlOperation(id: string): PaneControlOperation | null;
  claimAppliedPaneControlOperation(id: string): PaneControlOperation | null;
  rejectAppliedPaneControlOperation(id: string, detail: string): PaneControlOperation | null;
  getPaneControlOperation(id: string): PaneControlOperation | null;
  listRecoverablePaneControlOperations(): PaneControlOperation[];
  finishPaneControlOperation(id: string, state: PaneControlOutcome, detail?: string | null): boolean;
  finishPaneControlWithResult(input: {
    operationId: string;
    state: PaneControlOutcome;
    detail?: string | null;
    result: { kind: "card_reply" | "card_update"; targetMessageId: string; idempotencyKey: string; targetRole?: OutboundReply["targetRole"]; card: object };
  }): boolean;
  recoverRunningPrompts(): number;
  scanDurablePromptWork(): DurablePromptWorkScan;
  listDetachedPrompts(): PromptJob[];
  markPromptObservationDetached(id: string, notice: string): void;
  markPromptDispatched(id: string, dispatchedAt: string): void;
  markModelPromptPrepared(input: { bindingId: string; bindingGeneration: number; promptId: string; revision: number; operationId: string }): boolean;
  markModelPromptAccepted(input: { bindingId: string; bindingGeneration: number; promptId: string; revision: number; operationId: string; turnId: string }): boolean;
  rollbackPreparedModelPrompt(input: { bindingId: string; bindingGeneration: number; promptId: string; revision: number; operationId: string }): boolean;
  claimPromptTranscriptTurn(input: { promptId: string; bindingId: string; turnId: string; startedAt: string }): TranscriptTurnClaimOutcome;
  recoverLegacyElementIdDeadLetters(): number;
  enqueuePrompt(input: Omit<PromptJob, "state" | "observationState" | "attemptCount" | "error" | "createdAt" | "updatedAt" | "dispatchKind" | "parentPromptId" | "steeringOrigin" | "sourcePromptId" | "wasDetached" | "dispatchedAt" | "transcriptTurnId" | "transcriptTurnStartedAt" | "executionOrigin"> & Partial<Pick<PromptJob, "dispatchKind" | "parentPromptId" | "steeringOrigin" | "sourcePromptId" | "wasDetached" | "executionOrigin">>): { prompt: PromptJob; inserted: boolean };
  acceptPrompt(input: { prompt: Omit<PromptJob, "state" | "observationState" | "attemptCount" | "error" | "createdAt" | "updatedAt" | "dispatchKind" | "parentPromptId" | "steeringOrigin" | "sourcePromptId" | "wasDetached" | "dispatchedAt" | "transcriptTurnId" | "transcriptTurnStartedAt" | "executionOrigin"> & Partial<Pick<PromptJob, "dispatchKind" | "parentPromptId" | "steeringOrigin" | "sourcePromptId" | "wasDetached" | "executionOrigin">>; view: RunCardView; rootMessageId: string; taskCard?: object; answerCard: object }): { prompt: PromptJob; view: RunCardView; inserted: boolean };
  adoptExternalTurn(input: {
    bindingId: string; expectedGeneration: number; expectedPaneId: string; expectedSession: HerdrAgentSession;
    turnId: string; startedAt: string; requestText: string; externalPromptId: string; externalMessageId: string;
    supersede?: ExternalTurnSupersessionFence;
    externalView: RunCardView; answerCardFor(view: RunCardView): object;
  }): ExternalTurnAdoption;
  acceptClassifiedPrompt(input: ClassifiedPromptInput): ClassifiedPromptAcceptance;
  ensureAnswerCard(promptId: string, rootMessageId: string, card: object): void;
  getActiveAnswerPage(promptId: string): AnswerPage | null;
  listAnswerPages(promptId: string): AnswerPage[];
  getAnswerPageDeliveryFacts(promptId: string, pageIndex: number): AnswerPageDeliveryFacts;
  reserveAnswerContent(input: { promptId: string; pageIndex: number; cardId: string; elementId: string; content: string }): AnswerPageReservationOutcome;
  reserveAnswerFinish(input: { promptId: string; pageIndex: number; cardId: string; summary: string }): AnswerPageReservationOutcome;
  reserveAnswerContinuation(input: { promptId: string; pageIndex: number; cardId: string; summary: string; nextPageIndex: number; nextPageStart: number; nextElementId: string; rootMessageId: string; viewVersion: number; card: object }): AnswerPageReservationOutcome;
  reserveAnswerRebuild(input: { promptId: string; pageIndex: number; nextPageIndex: number; sourceStart: number; nextElementId: string; rootMessageId: string; viewVersion: number; card: object }): AnswerPageReservationOutcome;
  reserveFinalAnswerCardUpdate(input: { promptId: string; pageIndex: number; cardId: string; messageId: string; card: object }): AnswerPageReservationOutcome;
  reserveClosedAnswerCardUpdate(input: { promptId: string; pageIndex: number; messageId: string; card: object }): AnswerPageReservationOutcome;
  reserveStaticAnswerCardUpdate(input: { promptId: string; pageIndex: number; messageId: string; card: object }): AnswerPageReservationOutcome;
  reserveStaticAnswerReplacement(input: { promptId: string; previousPageIndex: number; nextPageIndex: number; sourceStart: number; nextElementId: string; rootMessageId: string; viewVersion: number; card: object }): AnswerPageReservationOutcome;
  claimNextDispatchablePrompt(bindingId: string): ClaimedPrompt | null;
  claimNextReadySteering(bindingId: string, parentPromptId: string): PromptJob | null;
  failQueuedSteering(bindingId: string, parentPromptId: string, notice: string): string[];
  cancelQueuedPromptsWithProjection(input: {
    bindingId: string;
    reason: string;
    occurredAt: string;
    rootMessageId: string | null;
    renderRunCard(view: RunCardView): object;
  }): { cancelledPromptIds: string[]; outboxReserved: boolean };
  updatePrompt(id: string, state: PromptJob["state"], error?: string | null): void;
  completeTurn(input: { promptId: string; bindingId: string; answer: string; occurredAt: string; outputFingerprint: string; replaceAnswer?: boolean }): Binding;
  failPrompt(input: { promptId: string; error: string; occurredAt: string; steeringFailureKind?: "rejected" | "uncertain" }): void;
  completeSteering(input: { promptId: string; notice: string; occurredAt: string }): void;
  enqueueOutboundReply(input: Omit<OutboundReply, "laneKey" | "promptId" | "workerTurnId" | "workerId" | "workerSessionGeneration" | "viewVersion" | "cardSequence" | "selectionId" | "cardRole" | "targetRole" | "state" | "attemptCount" | "error" | "deliveredMessageId" | "cardIdCheckpoint" | "failureClass" | "httpStatus" | "larkErrorCode" | "autoRecoveryCount" | "deadLetteredAt" | "nextAttemptAt" | "createdAt" | "updatedAt"> & { promptId?: string | null; workerTurnId?: string | null; workerId?: string | null; workerSessionGeneration?: number | null; viewVersion?: number | null; cardSequence?: number | null; selectionId?: string | null; cardRole?: OutboundReply["cardRole"]; targetRole?: OutboundReply["targetRole"] }): OutboundReply;
  hasPendingAnswerContinuation(promptId: string, pageIndex: number): boolean;
  dismissSupersededAnswerStream(replyId: string): boolean;
  listPendingOutboundReplies(): OutboundReply[];
  listOutboundLaneHeads(limit: number, dueAt: string | null, excludedLaneKeys?: readonly string[]): OutboundReply[];
  getNextOutboundLaneHeadAttemptAt(): string | null;
  markOutboundReplyDelivered(id: string, messageId: string, cardId?: string): void;
  checkpointOutboundReplyCard(id: string, cardId: string): OutboundReply | null;
  markOutboundReplyFailed(id: string, error: string, retryDelayMs?: number, metadata?: DeliveryFailureMetadata): OutboundReply | null;
  markOutboundReplyDeadLetter(id: string, error: string, metadata?: DeliveryFailureMetadata): OutboundReply | null;
  markOutboundReplyFailedWithQuarantine(id: string, error: string, metadata: DeliveryFailureMetadata, retryDelayMs?: number): OutboundFailureTransition | null;
  recoverEligibleDeadLetters(cutoff: string, limit: number): OutboundReply[];
  recoverStaleOutboxQuarantines(): StaleOutboxQuarantineRecovery;
  retryDeadLetter(id: string, chatId: string, actorOpenId: string): DeadLetterActionOutcome;
  dismissDeadLetter(id: string, chatId: string, actorOpenId: string): DeadLetterActionOutcome;
  pruneDeliveredOutboundReplies(cutoff: string, limit: number): number;
  pruneAcceptedInboundMessages(cutoff: string, limit: number): number;
  pruneTerminalSessionOperations(cutoff: string, limit: number): number;
  getOperationalSummary(): OperationalSummary;
  inspectIntegrity(limit: number, signal?: AbortSignal): SqliteIntegrityInspection;
  audit(input: { actorOpenId: string; action: string; target: string; outcome: string }): void;
  saveTopicView(view: TopicViewState): void;
  loadTopicView(bindingId: string): TopicViewState | null;
  reserveMainCard(view: TopicViewState, rootMessageId: string, card: object): MainCardReservationOutcome;
  saveRunCard(view: RunCardView): RunCardView;
  loadRunCard(promptId: string): RunCardView | null;
  listRunCards(bindingId: string): RunCardView[];
  listRunCardsByPhases(bindingId: string, phases: readonly RunCardView["phase"][]): RunCardView[];
}
