import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { randomUUID } from "node:crypto";
import type { Logger } from "pino";
import type { BridgeConfig } from "../config.js";
import { HerdrCliAdapter } from "../adapters/herdr-adapter.js";
import { LarkSdkAdapter } from "../adapters/lark-adapter.js";
import { InboundRouter } from "../coordinator/inbound-router.js";
import { InboundMessageDispatcher } from "../coordinator/inbound-message-dispatcher.js";
import { CardActionRouter } from "../coordinator/card-action-router.js";
import { InboundMessageRoutingWorkflow } from "../coordinator/inbound-message-routing-workflow.js";
import { BindingProvisioningWorkflow } from "../coordinator/binding-provisioning-workflow.js";
import { CardInteractionWorkflow } from "../coordinator/card-interaction-workflow.js";
import { HerdrRuntimeReconciler } from "../coordinator/herdr-runtime-reconciler.js";
import { ModelSelectionWorkflow } from "../coordinator/model-selection-workflow.js";
import { PaneControlWorkflow } from "../coordinator/pane-control-workflow.js";
import { OperationsQueryWorkflow } from "../coordinator/operations-query-workflow.js";
import { SessionAdministrationWorkflow } from "../coordinator/session-administration-workflow.js";
import { SessionOperationWorkflow } from "../coordinator/session-operation-workflow.js";
import { DeliveryRecoveryWorkflow } from "../coordinator/delivery-recovery-workflow.js";
import { PaneClosureWorkflow } from "../coordinator/pane-closure-workflow.js";
import { PaneRetentionWorkflow } from "../coordinator/pane-retention-workflow.js";
import { PromptRunWorkflow } from "../coordinator/prompt-run-workflow.js";
import { ExternalTurnObserver } from "../coordinator/external-turn-observer.js";
import { RetiredPaneCleanupWorkflow } from "../coordinator/retired-pane-cleanup-workflow.js";
import { StartupViewConverger } from "../coordinator/startup-view-converger.js";
import { StartupRecoveryWorkflow } from "../coordinator/startup-recovery-workflow.js";
import { AnswerPageWorkflow } from "../coordinator/answer-page-workflow.js";
import { MainCardWorkflow } from "../coordinator/main-card-workflow.js";
import { TurnControlWorkflow } from "../coordinator/turn-control-workflow.js";
import { InstanceControlWorkflow } from "../coordinator/instance-control-workflow.js";
import { InstanceMessagingWorkflow } from "../coordinator/instance-messaging-workflow.js";
import { InstanceInteractionWorkflow } from "../coordinator/instance-interaction-workflow.js";
import { InstanceRuntimeReconciler } from "../coordinator/instance-runtime-reconciler.js";
import { InstanceTurnSupervisor } from "../coordinator/instance-turn-supervisor.js";
import { WorkerTurnObserver } from "../coordinator/worker-turn-observer.js";
import { InstanceWorkScheduler } from "../events/instance-work-scheduler.js";
import { BridgeEventBus } from "../events/bridge-event-bus.js";
import { InProcessPromptWorkScheduler } from "../events/prompt-work-scheduler.js";
import { InProcessInboundWorkNotifier } from "../events/inbound-work-notifier.js";
import { ConversationViewProjector } from "../events/conversation-view-projector.js";
import { QueueFeedbackProjector } from "../events/queue-feedback-projector.js";
import { LarkOutboxDispatcher } from "../events/lark-outbox-dispatcher.js";
import { OutboundIntentWriter } from "../events/outbound-intent-writer.js";
import { InProcessOutboundWorkNotifier } from "../events/outbound-work-notifier.js";
import { ExecFileCommandRunner } from "../infra/command-runner.js";
import { WorkspaceSnapshotCache } from "../runtime/workspace-snapshot-cache.js";
import { HerdrCircuitBreaker } from "../runtime/herdr-circuit-breaker.js";
import { HerdrSocketSubscriber } from "../runtime/herdr-socket-subscriber.js";
import { HerdrEventRouter } from "../runtime/herdr-event-router.js";
import type { HerdrRuntimeHint } from "../runtime/herdr-event-hint.js";
import { OutboxRetentionMaintainer } from "../runtime/outbox-retention-maintainer.js";
import { SqliteIntegrityAuditor } from "../runtime/sqlite-integrity-auditor.js";
import { WorkerDatabaseIntegrityStore } from "../runtime/sqlite-integrity-worker.js";
import { WorktreeNameResolver } from "../runtime/worktree-name-resolver.js";
import { WorktreeManager } from "../runtime/worktree-manager.js";
import { HerdrPaneHost } from "../runtime/herdr/pane-host.js";
import { AgentDriverRegistry } from "../runtime/agents/agent-driver.js";
import { TraexDriver } from "../runtime/agents/traex-driver.js";
import { CodexDriver } from "../runtime/agents/codex-driver.js";
import { ClaudeCodeDriver } from "../runtime/agents/claude-code-driver.js";
import { PiDriver } from "../runtime/agents/pi-driver.js";
import { TraexTranscriptReader } from "../runtime/traex-transcript.js";
import { PrimaryToolGateway } from "../runtime/primary-tool-gateway.js";
import type { SqliteBindingStore } from "../store/sqlite-store.js";

export interface AgentRuntimeAvailability { codex: boolean; claude: boolean; pi: boolean; }

export function createBridgeRuntime(config: BridgeConfig, store: SqliteBindingStore, logger: Logger, availability: AgentRuntimeAvailability) {
  const runner = new ExecFileCommandRunner(config.commandTimeoutMs);
  const worktreeNameResolver = new WorktreeNameResolver(runner, config.commandTimeoutMs);
  let herdr!: WorkspaceSnapshotCache; let instanceRuntime!: InstanceRuntimeReconciler; let herdrEventRouter!: HerdrEventRouter;
  const herdrSocketSubscriber = process.env.HERDR_SOCKET_PATH ? new HerdrSocketSubscriber(process.env.HERDR_SOCKET_PATH, async () => { const ids = new Set(config.projects.map((project) => project.workspaceId)); return (await herdr.listAllPanes()).filter((pane) => ids.has(pane.workspaceId)).map((pane) => pane.paneId); }, async (hint: HerdrRuntimeHint) => herdrEventRouter.handle(hint), logger) : null;
  const rawHerdr = new HerdrCliAdapter(runner, config.herdr.executable, config.commandTimeoutMs, config.traex.permissionMode, herdrSocketSubscriber ?? undefined);
  const herdrCircuitBreaker = new HerdrCircuitBreaker(rawHerdr, config.herdrCircuitBreaker, logger);
  herdr = new WorkspaceSnapshotCache(herdrCircuitBreaker, config.runtimeTuning.herdrSnapshotCacheTtlMs, logger);
  const paneHost = new HerdrPaneHost(herdr);
  let wakeTurnControlOutbound: (() => void) | undefined;
  const turnControl = new TurnControlWorkflow({ store, herdr, idFactory: randomUUID, wakeOutbound: () => wakeTurnControlOutbound?.() });
  const agentDrivers = new AgentDriverRegistry([new TraexDriver(herdr, config.traex.executable, config.turnTimeoutMs), new CodexDriver(herdr, config.agents.codex, config.turnTimeoutMs, availability.codex), new ClaudeCodeDriver(herdr, config.agents.claudeCode, config.turnTimeoutMs, availability.claude), new PiDriver(herdr, config.agents.pi, config.turnTimeoutMs, availability.pi)]);
  const worktrees = new WorktreeManager(runner, { timeoutMs: config.commandTimeoutMs }); const lark = new LarkSdkAdapter(config.lark, logger); const bus = new BridgeEventBus(logger); const scheduler = new InProcessPromptWorkScheduler(logger); const inboundWork = new InProcessInboundWorkNotifier(); const outboundWork = new InProcessOutboundWorkNotifier(logger); wakeTurnControlOutbound = () => outboundWork.wake();
  const outbound = new OutboundIntentWriter(store, outboundWork); const transcriptReader = new TraexTranscriptReader({ sessionsRoot: config.traex.sessionsRoot });
  let instanceWork!: InstanceWorkScheduler; const workerTurns = new WorkerTurnObserver({ store, transcriptReader, wakeInstance: (instanceId) => instanceWork.wake(instanceId), wakeOutbound: () => outboundWork.wake() });
  instanceWork = new InstanceWorkScheduler({ store, drivers: agentDrivers, observer: workerTurns, wakeOutbound: () => outboundWork.wake(), logger });
  const instanceTurns = new InstanceTurnSupervisor({ store, paneHost, observer: workerTurns, wake: (instanceId) => instanceWork.wake(instanceId), wakeOutbound: () => outboundWork.wake(), logger });
  instanceRuntime = new InstanceRuntimeReconciler({ projects: config.projects, store, paneHost, wake: (instanceId) => instanceWork.wake(instanceId), logger });
  const instanceMessaging = new InstanceMessagingWorkflow({ store, drivers: agentDrivers, paneHost, turnControl, wake: (instanceId) => instanceWork.wake(instanceId), wakeOutbound: () => outboundWork.wake(), idFactory: randomUUID, maxQueueDepth: config.maxQueueDepth });
  const primaryToolGateway = new PrimaryToolGateway(join(dirname(config.databasePath), "primary-tools.sock"), process.execPath, [fileURLToPath(new URL("../cli/primary-tools-mcp.js", import.meta.url))], store, instanceMessaging, logger);
  const instanceControl = new InstanceControlWorkflow({ projects: config.projects, store, paneHost, drivers: agentDrivers, worktrees, idFactory: randomUUID }); const instanceInteractions = new InstanceInteractionWorkflow({ projects: config.projects, adminOpenIds: config.lark.adminOpenIds, store, control: instanceControl, messaging: instanceMessaging, drivers: agentDrivers, outbound });
  const channelPublisher = new LarkOutboxDispatcher(store, lark, logger, outboundWork, config.runtimeTuning.outboxSafetyScanIntervalMs); const answerPages = new AnswerPageWorkflow(store, () => outboundWork.wake(), logger); const mainCards = new MainCardWorkflow(store, () => outboundWork.wake(), logger);
  const outboxRetention = new OutboxRetentionMaintainer(store, { retentionDays: config.outboxRetention.days, batchSize: config.outboxRetention.batchSize, maxBatches: config.outboxRetention.maxBatches }, logger); const sqliteIntegrity = new SqliteIntegrityAuditor(new WorkerDatabaseIntegrityStore(config.databasePath), config.sqliteIntegrityAudit, logger);
  const projector = new ConversationViewProjector(bus, store, outbound, channelPublisher, logger, answerPages, mainCards, { cardUpdateDebounceMs: config.runtimeTuning.cardUpdateDebounceMs }); const queueFeedbackProjector = new QueueFeedbackProjector({ store, outboundWork, logger }); channelPublisher.connectPromptScheduler(scheduler);
  let promptRun!: PromptRunWorkflow; const externalTurns = new ExternalTurnObserver({ store, transcriptReader, bus, outboundWork, logger, isBindingBusy: (bindingId) => promptRun.isBindingBusy(bindingId), wakePrompt: (bindingId) => scheduler.wake({ kind: "prompt-ready", bindingId }) });
  promptRun = new PromptRunWorkflow({ store, herdr, bus, scheduler, outboundWork, logger, turnTimeoutMs: config.turnTimeoutMs, transcriptReader, handoffExternalTurns: (bindingId) => externalTurns.handoff(bindingId), observeSupersedingExternalTurn: (binding, prompt, observation) => externalTurns.observeSupersedingTurn(binding, prompt, observation), recoverExternalTurns: (binding, prompt) => externalTurns.recoverAfterDetachedTurn(binding, prompt) });
  const retiredPaneCleanup = new RetiredPaneCleanupWorkflow({ store, herdr, logger }); const provisioning = new BindingProvisioningWorkflow({ config, store, herdr, lark, lifecycleEvents: bus, outbound, outboundWork, immediateOutbound: channelPublisher, scheduler, primaryTools: primaryToolGateway, wakeRetiredPaneCleanup: () => void retiredPaneCleanup.requestScan(), logger }); const modelSelection = new ModelSelectionWorkflow({ config, store, herdr, outbound, outboundWork, scheduler, activeTurn: (bindingId) => promptRun.activeTurn(bindingId), logger }); const paneControl = new PaneControlWorkflow({ store, herdr, outbound, scheduler, model: modelSelection, turnControl, activeTurn: (bindingId) => promptRun.activeTurn(bindingId) }); const operationsQuery = new OperationsQueryWorkflow({ config, store, herdr, outbound, logger }); const sessionAdministration = new SessionAdministrationWorkflow({ config, store, herdr, lifecycleEvents: bus, outbound, outboundWork, scheduler, isBindingBusy: (bindingId) => promptRun.isBindingBusy(bindingId) }); const deliveryRecovery = new DeliveryRecoveryWorkflow({ store, lark, outbound, outboundWork, logger }); const paneClosure = new PaneClosureWorkflow({ config, store, herdr, lifecycleEvents: bus, outbound, isBindingBusy: (bindingId) => promptRun.isBindingBusy(bindingId) }); const paneRetention = new PaneRetentionWorkflow({ projects: config.projects, store, herdr, outbound, isBindingBusy: (bindingId) => promptRun.isBindingBusy(bindingId), logger });
  const sessionOperations = new SessionOperationWorkflow({ store, sessionAdministration, provisioning, paneControl, paneClosure, logger }); const cardInteractions = new CardInteractionWorkflow({ store, adminOpenIds: config.lark.adminOpenIds, sessionAdministration, sessionOperations, wakePrompt: (bindingId) => scheduler.wake({ kind: "prompt-ready", bindingId }), logger });
  const reconciler = new HerdrRuntimeReconciler({ projects: config.projects, store, herdr, lifecycleEvents: bus, channelPublisher: outbound, logger, wakeOutbound: () => outboundWork.wake(), convergeAnswer: (promptId) => answerPages.converge(promptId), discoverPane: (pane, project) => provisioning.discover(pane, project), scheduler, isBindingBusy: (bindingId) => promptRun.isBindingBusy(bindingId), externalTurnObserver: externalTurns, worktreeNameFor: (cwd) => worktreeNameResolver.resolve(cwd) });
  herdrEventRouter = new HerdrEventRouter({ invalidateWorkspace: (workspaceId) => herdr.invalidate(workspaceId), reconcileBindings: async (scope) => { if (scope?.paneIds) await reconciler.requestPaneReconciliation(scope.paneIds); else await reconciler.requestReconciliation(scope?.workspaceIds); }, reconcileInstances: (scope) => instanceRuntime.requestReconciliation(scope), observeInstanceTurns: (paneIds) => paneIds ? instanceTurns.requestObservationByPane(paneIds) : instanceTurns.reconcile(), retryRetiredPanes: (paneIds) => paneIds ? retiredPaneCleanup.requestPanes(paneIds) : retiredPaneCleanup.requestScan(), logger });
  const startupViews = new StartupViewConverger(config, store, outbound, outboundWork, answerPages, mainCards, logger); const inboundDispatcher = new InboundMessageDispatcher({ chatId: config.lark.chatId, allowedOpenIds: config.lark.allowedOpenIds, store, inboundWork, logger }); const messageRouting = new InboundMessageRoutingWorkflow({ config, store, lifecycleEvents: bus, outbound, outboundWork, logger, scheduler, promptRun, provisioning, modelSelection, paneControl, operationsQuery, sessionAdministration, paneClosure, instanceInteractions }); const cardActionRouter = new CardActionRouter({ chatId: config.lark.chatId, allowedOpenIds: config.lark.allowedOpenIds, adminOpenIds: config.lark.adminOpenIds, projects: config.projects, store, provisioning, cardInteractions, modelSelection, deliveryRecovery, instanceInteractions, logger, enqueueInitialPrompt: (binding, selection) => messageRouting.enqueueInitialProjectPrompt(binding, selection) }); const startupRecovery = new StartupRecoveryWorkflow({ config, store, herdr, lark, logger, scheduler, inboundWork, inboundDispatcher, cardActionRouter, messageRouting, promptRun, provisioning, paneControl, paneClosure, sessionOperations, reconciler, retiredPaneCleanup, startupViews }); const coordinator = new InboundRouter({ lark, modelSelection, promptRun, reconciler, retiredPaneCleanup, sessionOperations, inboundDispatcher, cardActionRouter, startupRecovery });
  const instanceWorker = { snapshot() { const dispatch = instanceWork.snapshot(); const observe = instanceTurns.snapshot(); return { state: dispatch.state, activeDispatchWorkers: dispatch.activeDispatchWorkers, activeObservers: observe.activeObservers, queuedTurns: observe.queuedTurns, activeTurns: observe.activeTurns, uncertainTurns: observe.uncertainTurns, lastScanAt: observe.lastScanAt, lastFailureAt: dispatch.lastFailureAt ?? observe.lastFailureAt, lastFailure: dispatch.lastFailure ?? observe.lastFailure }; } };
  return { herdr, herdrCircuitBreaker, herdrSocketSubscriber, instanceRuntime, instanceTurns, instanceWork, primaryToolGateway, sqliteIntegrity, coordinator, queueFeedbackProjector, projector, channelPublisher, outboxRetention, paneRetention, externalTurns, instanceWorker, lark, bus, sessionOperations, reconciler, promptRun };
}
