import type { Logger } from "pino";
import type { BridgeConfig } from "../config.js";
import { cardKitPanePresentation } from "../cards/cardkit-pane-presentation.js";
import { cardKitPrimaryPresentation } from "../cards/cardkit-primary-presentation.js";
import { cardKitApplicationPresentation } from "../cards/cardkit-application-presentation.js";
import { BindingProvisioningWorkflow } from "../coordinator/binding-provisioning-workflow.js";
import { CardActionRouter } from "../coordinator/card-action-router.js";
import { CardInteractionWorkflow } from "../coordinator/card-interaction-workflow.js";
import { DeliveryRecoveryWorkflow } from "../coordinator/delivery-recovery-workflow.js";
import { HerdrRuntimeReconciler } from "../coordinator/herdr-runtime-reconciler.js";
import { InboundMessageDispatcher } from "../coordinator/inbound-message-dispatcher.js";
import { InboundMessageRoutingWorkflow } from "../coordinator/inbound-message-routing-workflow.js";
import { InboundRouter } from "../coordinator/inbound-router.js";
import { InstanceInteractionWorkflow } from "../coordinator/instance-interaction-workflow.js";
import { ModelSelectionWorkflow } from "../coordinator/model-selection-workflow.js";
import { OperationsQueryWorkflow } from "../coordinator/operations-query-workflow.js";
import { PaneClosureWorkflow } from "../coordinator/pane-closure-workflow.js";
import { PaneControlWorkflow } from "../coordinator/pane-control-workflow.js";
import { PaneRetentionWorkflow } from "../coordinator/pane-retention-workflow.js";
import { RetiredPaneCleanupWorkflow } from "../coordinator/retired-pane-cleanup-workflow.js";
import { SessionAdministrationWorkflow } from "../coordinator/session-administration-workflow.js";
import { SessionOperationWorkflow } from "../coordinator/session-operation-workflow.js";
import { StartupRecoveryWorkflow } from "../coordinator/startup-recovery-workflow.js";
import { StartupViewConverger } from "../coordinator/startup-view-converger.js";
import { SwarmCommandContextResolver } from "../coordinator/swarm-command-context-resolver.js";
import { SwarmCommandGateway } from "../coordinator/swarm-command-gateway.js";
import type { TurnControlWorkflow } from "../coordinator/turn-control-workflow.js";
import type { BridgeEventBus } from "../events/bridge-event-bus.js";
import type { InProcessInboundWorkNotifier } from "../events/inbound-work-notifier.js";
import type { InProcessPromptWorkScheduler } from "../events/prompt-work-scheduler.js";
import { HerdrEventRouter } from "../runtime/herdr-event-router.js";
import type { SqliteBindingStore } from "../store/sqlite-store.js";
import type { createInfrastructureRuntime } from "./create-infrastructure-runtime.js";
import type { createOutboundRuntime } from "./create-outbound-runtime.js";
import type { createPrimaryRuntime } from "./create-primary-runtime.js";
import type { createWorkerRuntime } from "./create-worker-runtime.js";

export function createApplicationRuntime(options: {
  config: BridgeConfig; store: SqliteBindingStore; logger: Logger; turnControl: TurnControlWorkflow;
  bus: BridgeEventBus; scheduler: InProcessPromptWorkScheduler; inboundWork: InProcessInboundWorkNotifier;
  infrastructure: ReturnType<typeof createInfrastructureRuntime>; delivery: ReturnType<typeof createOutboundRuntime>;
  primary: ReturnType<typeof createPrimaryRuntime>; worker: ReturnType<typeof createWorkerRuntime>;
}) {
  const { config, store, logger, turnControl, bus, scheduler, inboundWork, infrastructure, delivery, primary, worker } = options;
  const { herdr, lark, worktreeNameResolver, agentDrivers } = infrastructure;
  const { outbound, outboundWork, channelPublisher, answerPages, mainCards } = delivery;
  const { promptRun, externalTurns } = primary;
  const { instanceRuntime, instanceTurns, instanceMessaging, instanceControl } = worker;
  const retiredPaneCleanup = new RetiredPaneCleanupWorkflow({ store, herdr, logger });
  const provisioning = new BindingProvisioningWorkflow({ config, store, herdr, lark, lifecycleEvents: bus, outbound, outboundWork, immediateOutbound: channelPublisher, scheduler, primaryTools: worker.primaryToolGateway, wakeRetiredPaneCleanup: () => void retiredPaneCleanup.requestScan(), presentation: cardKitApplicationPresentation, logger });
  const modelSelection = new ModelSelectionWorkflow({ config, store, herdr, outbound, outboundWork, scheduler, mainCards, activeTurn: (bindingId) => promptRun.activeTurn(bindingId), presentation: cardKitApplicationPresentation, logger });
  const paneControl = new PaneControlWorkflow({ store, outbound, presentation: cardKitPanePresentation, scheduler, model: modelSelection, turnControl, activeTurn: (bindingId) => promptRun.activeTurn(bindingId) });
  const operationsQuery = new OperationsQueryWorkflow({ config, store, herdr, outbound, presentation: cardKitApplicationPresentation, logger });
  const sessionAdministration = new SessionAdministrationWorkflow({ config, store, herdr, lifecycleEvents: bus, outbound, outboundWork, scheduler, isBindingBusy: (bindingId) => promptRun.isBindingBusy(bindingId), presentation: cardKitApplicationPresentation });
  const deliveryRecovery = new DeliveryRecoveryWorkflow({ store, lark, outbound, outboundWork, presentation: cardKitApplicationPresentation, logger });
  const paneClosure = new PaneClosureWorkflow({ config, store, herdr, lifecycleEvents: bus, outbound, presentation: cardKitPanePresentation, isBindingBusy: (bindingId) => promptRun.isBindingBusy(bindingId) });
  const paneRetention = new PaneRetentionWorkflow({ projects: config.projects, store, herdr, outbound, presentation: cardKitPanePresentation, isBindingBusy: (bindingId) => promptRun.isBindingBusy(bindingId), logger });
  const sessionOperations = new SessionOperationWorkflow({ store, sessionAdministration, provisioning, paneControl, paneClosure, logger });
  const cardInteractions = new CardInteractionWorkflow({ store, adminOpenIds: config.lark.adminOpenIds, sessionAdministration, sessionOperations, wakePrompt: (bindingId) => scheduler.wake({ kind: "prompt-ready", bindingId }), presentation: cardKitApplicationPresentation, logger });
  const reconciler = new HerdrRuntimeReconciler({ projects: config.projects, store, herdr, lifecycleEvents: bus, channelPublisher: outbound, logger, wakeOutbound: () => outboundWork.wake(), convergeAnswer: (promptId) => answerPages.converge(promptId), discoverPane: (pane, project) => provisioning.discover(pane, project), scheduler, isBindingBusy: (bindingId) => promptRun.isBindingBusy(bindingId), externalTurnObserver: externalTurns, worktreeNameFor: (cwd) => worktreeNameResolver.resolve(cwd), presentation: cardKitApplicationPresentation });
  const herdrEventRouter = new HerdrEventRouter({ invalidateWorkspace: (workspaceId) => herdr.invalidate(workspaceId), reconcileBindings: async (scope) => { if (scope?.paneIds) await reconciler.requestPaneReconciliation(scope.paneIds); else await reconciler.requestReconciliation(scope?.workspaceIds); }, reconcileInstances: (scope) => instanceRuntime.requestReconciliation(scope), observeInstanceTurns: (paneIds) => paneIds ? instanceTurns.requestObservationByPane(paneIds) : instanceTurns.reconcile(), retryRetiredPanes: (paneIds) => paneIds ? retiredPaneCleanup.requestPanes(paneIds) : retiredPaneCleanup.requestScan(), logger });
  const commandResolver = new SwarmCommandContextResolver({ config, store, activeTurn: (bindingId) => promptRun.activeTurn(bindingId) });
  const swarmCommands = new SwarmCommandGateway({ store, resolver: commandResolver, outbound, logger, provisioning, modelSelection, paneControl, operationsQuery, sessionAdministration, paneClosure, promptRun, instanceControl, presentation: cardKitApplicationPresentation });
  const instanceInteractions = new InstanceInteractionWorkflow({ projects: config.projects, adminOpenIds: config.lark.adminOpenIds, store, control: instanceControl, messaging: instanceMessaging, drivers: agentDrivers, outbound, workerCreation: swarmCommands, presentation: cardKitApplicationPresentation });
  const startupViews = new StartupViewConverger(config, store, outbound, outboundWork, cardKitPrimaryPresentation, answerPages, mainCards, logger);
  const inboundDispatcher = new InboundMessageDispatcher({ chatId: config.lark.chatId, allowedOpenIds: config.lark.allowedOpenIds, store, inboundWork, logger });
  const messageRouting = new InboundMessageRoutingWorkflow({ config, store, lifecycleEvents: bus, outbound, outboundWork, logger, scheduler, presentation: cardKitPrimaryPresentation, promptRun, provisioning, swarmCommands, instanceInteractions });
  const cardActionRouter = new CardActionRouter({ chatId: config.lark.chatId, allowedOpenIds: config.lark.allowedOpenIds, adminOpenIds: config.lark.adminOpenIds, projects: config.projects, store, provisioning, cardInteractions, modelSelection, deliveryRecovery, instanceInteractions, logger, enqueueInitialPrompt: (binding, selection) => messageRouting.enqueueInitialProjectPrompt(binding, selection) });
  const startupRecovery = new StartupRecoveryWorkflow({ config, store, herdr, lark, logger, scheduler, inboundWork, inboundDispatcher, cardActionRouter, messageRouting, promptRun, provisioning, paneControl, paneClosure, sessionOperations, swarmCommands, reconciler, retiredPaneCleanup, startupViews });
  const coordinator = new InboundRouter({ lark, modelSelection, promptRun, reconciler, retiredPaneCleanup, sessionOperations, swarmCommands, inboundDispatcher, cardActionRouter, startupRecovery });
  return { coordinator, paneRetention, sessionOperations, reconciler, retiredPaneCleanup, herdrEventRouter };
}
