import type {
  AgentState, AnswerPage, AnswerPageDeliveryMode, AnswerPageState, Binding, BindingState, CardInteraction, CardInteractionActionKind, CardInteractionState, DeliveryFailureClass,
  BindingThreadAlias, OutboundReply, OutboundReplyKind, OutboundReplyState, OutboundTargetRole, OutboundWorkClass, PaneControlOperation,
  PaneControlOperationKind, PaneControlOperationState, ProjectSelection, ProjectSelectionState,
  PromptJob, PromptObservationState, PromptState, RequestCardRole, TurnPriority,
  RetiredPaneCleanupOperation, RetiredPaneCleanupState, SessionOperation, SessionOperationKind, SessionOperationState
} from "../domain/types.js";
import type { ModelPreference, ModelPreferenceState } from "../domain/model-selection.js";
import type { AttachmentState, ProvisioningCheckpoint, SessionLifecycle } from "../domain/pane-thread-lifecycle.js";
import type { TurnControlKind, TurnControlOperation, TurnControlState } from "../domain/turn-control.js";
import type { ControlActor } from "../domain/commands.js";
import type { CommandIntent, CommandIntentState } from "../domain/command-intent.js";
import type { NaturalLanguageCommandConfirmation, NaturalLanguageCommandConfirmationState } from "../domain/natural-language-command-confirmation.js";
import type { BridgeCommand } from "../domain/types.js";
import type { SwarmCommandContext, SwarmCommandReplayPolicy } from "../domain/swarm-command.js";
import type { InstanceLease } from "../domain/types.js";
import type { WorkerSessionThread } from "../domain/worker-session-thread.js";
import type { AgentKind } from "../domain/agent-instance.js";

export type SqlValue = string | number | bigint | null;
export type BindingRow = Record<string, SqlValue> & {
  id: string; gateway_id: string; creator_open_id: string | null; project_id: string | null; workspace_id: string; chat_id: string; topic_id: string | null; root_message_id: string | null;
  retired_topic_id: string | null; retired_root_message_id: string | null; replaces_binding_id: string | null; reserved_topic_id: string | null;
  reserved_root_message_id: string | null; reset_message_id: string | null; pane_id: string | null; traex_session_id: string | null;
  agent_session_source: string | null; agent_session_agent: string | null; agent_session_kind: string | null; agent_session_value: string | null;
  title: string; runtime: string; agent_kind: string; state: string; status_message_id: string | null; status_card_sequence: number; last_agent_state: string; last_output_fingerprint: string | null;
  lifecycle: string; attachment: string; generation: number; provisioning_checkpoint: string; degradation_count: number; has_completed_turn: number;
  last_observed_at: string | null; archived_at: string | null; last_activity_at: string; created_at: string; updated_at: string;
};
export type PromptRow = Record<string, SqlValue> & { id: string; binding_id: string; lark_message_id: string; actor_open_id: string; body: string; parent_prompt_id: string | null; execution_origin: string; state: string; priority: string; was_detached: number; dispatched_at: string | null; transcript_turn_id: string | null; transcript_turn_started_at: string | null; model_name: string | null; model_revision: number | null; observation_state: string; attempt_count: number; error: string | null; created_at: string; updated_at: string; };
export type ModelPreferenceRow = Record<string, SqlValue> & { binding_id: string; binding_generation: number; desired_model: string; desired_revision: number; effective_model: string | null; effective_revision: number | null; state: string; dispatch_prompt_id: string | null; prepared_operation_id: string | null; updated_at: string; };
export type OutboundReplyRow = Record<string, SqlValue> & { id: string; gateway_id: string; gateway_profile_id: string; gateway_plan_json: string | null; gateway_plan_hash: string | null; gateway_checkpoint_json: string | null; idempotency_key: string; binding_id: string | null; prompt_id: string | null; worker_turn_id: string | null; worker_id: string | null; worker_session_generation: number | null; view_version: number | null; card_sequence: number | null; selection_id: string | null; card_role: string | null; target_role: string | null; thread_alias_id: string | null; worker_thread_id: string | null; target_chat_id: string | null; work_class: string; root_message_id: string | null; kind: string; payload: string; intent_kind: string | null; intent_json: string | null; renderer_revision: number | null; state: string; attempt_count: number; error: string | null; delivered_message_id: string | null; next_attempt_at: string; created_at: string; updated_at: string; card_id_checkpoint: string | null; delivery_order: number; lane_key: string; failure_class: string | null; effect_certainty: string | null; http_status: number | null; lark_error_code: string | null; auto_recovery_count: number; dead_lettered_at: string | null; };
export type BindingThreadAliasRow = Record<string, SqlValue> & { id: string; publication_key: string; binding_id: string; binding_generation: number; chat_id: string; pane_id: string; source_main_message_id: string; action_message_id: string; topic_id: string | null; root_message_id: string | null; state: string; created_at: string; updated_at: string };
export type WorkerSessionThreadRow = Record<string, SqlValue> & { id: string; publication_key: string; worker_id: string; worker_session_generation: number; parent_binding_id: string; parent_binding_generation: number; parent_pane_id: string; chat_id: string; mode: string; source_main_message_id: string | null; action_message_id: string | null; topic_id: string | null; root_message_id: string | null; state: string; created_at: string; activated_at: string | null; stale_at: string | null; updated_at: string };
export type AnswerPageRow = Record<string, SqlValue> & { prompt_id: string; page_index: number; message_id: string | null; card_id: string | null; element_id: string; source_start: number; sequence: number; state: string; delivery_mode: string; created_at: string; updated_at: string; };
export type ProjectSelectionRow = Record<string, SqlValue> & { id: string; command_message_id: string; selector_message_id: string | null; chat_id: string; topic_id: string | null; root_message_id: string; actor_open_id: string; requested_title: string | null; initial_prompt_text: string | null; agent_kind: string; selected_project_id: string | null; binding_id: string | null; state: string; error: string | null; expires_at: string; created_at: string; updated_at: string; };
export type RetiredPaneCleanupRow = Record<string, SqlValue> & { id: string; old_binding_id: string; replacement_binding_id: string; pane_id: string; expected_workspace_id: string; expected_project_id: string; expected_cwd: string; expected_terminal_id: string; actor_open_id: string; state: string; attempt_count: number; detail: string | null; created_at: string; updated_at: string; };
export type PaneControlOperationRow = Record<string, SqlValue> & { id: string; idempotency_key: string; binding_id: string; pane_id: string; terminal_id: string | null; binding_generation: number; kind: string; payload: string | null; parent_prompt_id: string | null; state: string; attempt_count: number; detail: string | null; actor_open_id: string; source_message_id: string; created_at: string; updated_at: string; };
export type CardInteractionRow = Record<string, SqlValue> & { id: string; binding_id: string; binding_generation: number; actor_open_id: string; action_kind: string; parent_prompt_id: string | null; target_prompt_id: string | null; state: string; expires_at: string; result_code: string | null; created_at: string; claimed_at: string | null; consumed_at: string | null; };
export type SessionOperationRow = Record<string, SqlValue> & { id: string; idempotency_key: string; interaction_id: string; binding_id: string; binding_generation: number; expected_pane_id: string | null; expected_terminal_id: string | null; actor_open_id: string; kind: string; argument: string | null; state: string; attempt_count: number; detail: string | null; created_at: string; updated_at: string; };
export type CommandIntentRow = Record<string, SqlValue> & { id: string; idempotency_key: string; lane_key: string; command_json: string; context_json: string; replay_policy: string; state: string; attempt_count: number; outcome_json: string | null; claimed_at: string | null; created_at: string; updated_at: string; };
export type NaturalLanguageCommandConfirmationRow = Record<string, SqlValue> & { id: string; source_message_id: string; actor_open_id: string; chat_id: string; topic_id: string | null; root_message_id: string; command_json: string; expected_binding_id: string | null; expected_binding_generation: number | null; expected_instance_id: string | null; expected_instance_generation: number | null; state: string; expires_at: string; result_detail: string | null; created_at: string; updated_at: string; resolved_at: string | null };
export type TurnControlOperationRow = Record<string, SqlValue> & { id: string; idempotency_key: string; kind: string; owner_kind: string; owner_id: string; project_id: string; pane_id: string; generation: number; agent_session_source: string; agent_session_agent: string; agent_session_kind: string; agent_session_value: string; logical_turn_id: string; runtime_turn_id: string; actor_json: string; payload: string | null; source_message_id: string | null; source_card_id: string | null; state: string; result_json: string | null; created_at: string; updated_at: string; };

export function mapInstanceLease(row: { owner_id: string; fencing_token: number; expires_at: string; updated_at: string }): InstanceLease { return { ownerId: row.owner_id, fencingToken: Number(row.fencing_token), expiresAt: row.expires_at, updatedAt: row.updated_at }; }

export function mapPaneControlOperation(row: PaneControlOperationRow): PaneControlOperation { return { id: row.id, idempotencyKey: row.idempotency_key, bindingId: row.binding_id, paneId: row.pane_id, terminalId: row.terminal_id, bindingGeneration: Number(row.binding_generation), kind: row.kind as PaneControlOperationKind, payload: row.payload, parentPromptId: row.parent_prompt_id, state: row.state as PaneControlOperationState, attemptCount: Number(row.attempt_count), detail: row.detail, actorOpenId: row.actor_open_id, sourceMessageId: row.source_message_id, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapBinding(row: BindingRow): Binding { return { id: row.id, gatewayId: row.gateway_id ?? "feishu:primary", creatorOpenId: row.creator_open_id ?? null, projectId: row.project_id, workspaceId: row.workspace_id, chatId: row.chat_id, topicId: row.topic_id, rootMessageId: row.root_message_id, retiredTopicId: row.retired_topic_id ?? null, retiredRootMessageId: row.retired_root_message_id ?? null, replacesBindingId: row.replaces_binding_id ?? null, reservedTopicId: row.reserved_topic_id ?? null, reservedRootMessageId: row.reserved_root_message_id ?? null, resetMessageId: row.reset_message_id ?? null, paneId: row.pane_id, traexSessionId: row.traex_session_id, agentSessionSource: row.agent_session_source ?? null, agentSessionAgent: row.agent_session_agent ?? null, agentSessionKind: row.agent_session_kind as "id" | "path" | null, agentSessionValue: row.agent_session_value ?? null, title: row.title, agentKind: (row.agent_kind ?? "traex") as AgentKind, state: row.state as BindingState, statusMessageId: row.status_message_id, statusCardSequence: Number(row.status_card_sequence ?? 0), lastAgentState: row.last_agent_state as AgentState, lastOutputFingerprint: row.last_output_fingerprint, lifecycle: row.lifecycle as SessionLifecycle, attachment: row.attachment as AttachmentState, generation: Number(row.generation), provisioningCheckpoint: row.provisioning_checkpoint as ProvisioningCheckpoint, degradationCount: Number(row.degradation_count), hasCompletedTurn: Boolean(row.has_completed_turn), lastObservedAt: row.last_observed_at, archivedAt: row.archived_at, lastActivityAt: row.last_activity_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapCardInteraction(row: CardInteractionRow): CardInteraction { return { id: row.id, bindingId: row.binding_id, bindingGeneration: Number(row.binding_generation), actorOpenId: row.actor_open_id, actionKind: row.action_kind as CardInteractionActionKind, parentPromptId: row.parent_prompt_id, targetPromptId: row.target_prompt_id, state: row.state as CardInteractionState, expiresAt: row.expires_at, resultCode: row.result_code, createdAt: row.created_at, claimedAt: row.claimed_at, consumedAt: row.consumed_at }; }
export function mapSessionOperation(row: SessionOperationRow): SessionOperation { return { id: row.id, idempotencyKey: row.idempotency_key, interactionId: row.interaction_id, bindingId: row.binding_id, bindingGeneration: Number(row.binding_generation), expectedPaneId: row.expected_pane_id, expectedTerminalId: row.expected_terminal_id, actorOpenId: row.actor_open_id, kind: row.kind as SessionOperationKind, argument: row.argument, state: row.state as SessionOperationState, attemptCount: Number(row.attempt_count), detail: row.detail, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapCommandIntent(row: CommandIntentRow): CommandIntent { return { id: row.id, idempotencyKey: row.idempotency_key, laneKey: row.lane_key, command: JSON.parse(row.command_json) as BridgeCommand, context: JSON.parse(row.context_json) as SwarmCommandContext, replayPolicy: row.replay_policy as SwarmCommandReplayPolicy, state: row.state as CommandIntentState, attemptCount: Number(row.attempt_count), outcome: row.outcome_json === null ? null : JSON.parse(row.outcome_json) as CommandIntent["outcome"], claimedAt: row.claimed_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapNaturalLanguageCommandConfirmation(row: NaturalLanguageCommandConfirmationRow): NaturalLanguageCommandConfirmation { return { id: row.id, sourceMessageId: row.source_message_id, actorOpenId: row.actor_open_id, chatId: row.chat_id, topicId: row.topic_id, rootMessageId: row.root_message_id, envelope: JSON.parse(row.command_json) as NaturalLanguageCommandConfirmation["envelope"], expectedBindingId: row.expected_binding_id, expectedBindingGeneration: row.expected_binding_generation === null ? null : Number(row.expected_binding_generation), expectedInstanceId: row.expected_instance_id, expectedInstanceGeneration: row.expected_instance_generation === null ? null : Number(row.expected_instance_generation), state: row.state as NaturalLanguageCommandConfirmationState, expiresAt: row.expires_at, resultDetail: row.result_detail, createdAt: row.created_at, updatedAt: row.updated_at, resolvedAt: row.resolved_at }; }
export function mapTurnControlOperation(row: TurnControlOperationRow): TurnControlOperation {
  return {
    id: row.id, idempotencyKey: row.idempotency_key, kind: row.kind as TurnControlKind,
    target: {
      owner: row.owner_kind === "binding" ? { kind: "binding", id: row.owner_id } : { kind: "instance", id: row.owner_id },
      projectId: row.project_id, paneId: row.pane_id, generation: Number(row.generation),
      agentSession: { source: row.agent_session_source, agent: row.agent_session_agent, kind: row.agent_session_kind as "id" | "path", value: row.agent_session_value },
      logicalTurnId: row.logical_turn_id, runtimeTurnId: row.runtime_turn_id
    },
    actor: JSON.parse(row.actor_json) as ControlActor, payload: row.payload, sourceMessageId: row.source_message_id, sourceCardId: row.source_card_id,
    state: row.state as TurnControlState, result: row.result_json === null ? null : JSON.parse(row.result_json) as Record<string, unknown>,
    createdAt: row.created_at, updatedAt: row.updated_at
  };
}
export function mapRetiredPaneCleanup(row: RetiredPaneCleanupRow): RetiredPaneCleanupOperation { return { id: row.id, oldBindingId: row.old_binding_id, replacementBindingId: row.replacement_binding_id, paneId: row.pane_id, expectedWorkspaceId: row.expected_workspace_id, expectedProjectId: row.expected_project_id, expectedCwd: row.expected_cwd, expectedTerminalId: row.expected_terminal_id, actorOpenId: row.actor_open_id, state: row.state as RetiredPaneCleanupState, attemptCount: Number(row.attempt_count), detail: row.detail, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapPrompt(row: PromptRow): PromptJob { return { id: row.id, bindingId: row.binding_id, larkMessageId: row.lark_message_id, actorOpenId: row.actor_open_id, body: row.body, parentPromptId: row.parent_prompt_id ?? null, executionOrigin: row.execution_origin as PromptJob["executionOrigin"], priority: (row.priority ?? "normal") as TurnPriority, wasDetached: Boolean(row.was_detached), dispatchedAt: row.dispatched_at, transcriptTurnId: row.transcript_turn_id, transcriptTurnStartedAt: row.transcript_turn_started_at, modelName: row.model_name ?? null, modelRevision: row.model_revision === null || row.model_revision === undefined ? null : Number(row.model_revision), observationState: row.observation_state as PromptObservationState, state: row.state as PromptState, attemptCount: Number(row.attempt_count), error: row.error, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapModelPreference(row: ModelPreferenceRow): ModelPreference { return { bindingId: row.binding_id, bindingGeneration: Number(row.binding_generation), desiredModel: row.desired_model, desiredRevision: Number(row.desired_revision), effectiveModel: row.effective_model, effectiveRevision: row.effective_revision === null ? null : Number(row.effective_revision), state: row.state as ModelPreferenceState, dispatchPromptId: row.dispatch_prompt_id, preparedOperationId: row.prepared_operation_id, updatedAt: row.updated_at }; }
export function mapOutboundReply(row: OutboundReplyRow): OutboundReply { return { id: row.id, gatewayId: row.gateway_id ?? "feishu:primary", gatewayProfileId: row.gateway_profile_id ?? "feishu-cardkit-v1", gatewayPlanJson: row.gateway_plan_json ?? null, gatewayPlanHash: row.gateway_plan_hash ?? null, gatewayCheckpointJson: row.gateway_checkpoint_json ?? null, idempotencyKey: row.idempotency_key, bindingId: row.binding_id, rootMessageId: row.root_message_id, promptId: row.prompt_id, workerTurnId: row.worker_turn_id ?? null, workerId: row.worker_id ?? null, workerSessionGeneration: row.worker_session_generation === null || row.worker_session_generation === undefined ? null : Number(row.worker_session_generation), viewVersion: row.view_version === null ? null : Number(row.view_version), cardSequence: row.card_sequence === null ? null : Number(row.card_sequence), selectionId: row.selection_id, cardRole: row.card_role as RequestCardRole | null, targetRole: row.target_role as OutboundTargetRole | null, threadAliasId: row.thread_alias_id ?? null, workerThreadId: row.worker_thread_id ?? null, targetChatId: row.target_chat_id ?? null, laneKey: row.lane_key, workClass: row.work_class as OutboundWorkClass, kind: row.kind as OutboundReplyKind, payload: row.payload, intentKind: row.intent_kind as OutboundReply["intentKind"] ?? null, intentJson: row.intent_json ?? null, rendererRevision: row.renderer_revision === null || row.renderer_revision === undefined ? null : Number(row.renderer_revision), state: row.state as OutboundReplyState, attemptCount: Number(row.attempt_count), error: row.error, deliveredMessageId: row.delivered_message_id, cardIdCheckpoint: row.card_id_checkpoint ?? null, failureClass: row.failure_class as DeliveryFailureClass | null, effectCertainty: row.effect_certainty as OutboundReply["effectCertainty"] ?? null, httpStatus: row.http_status === null ? null : Number(row.http_status), larkErrorCode: row.lark_error_code, autoRecoveryCount: Number(row.auto_recovery_count ?? 0), deadLetteredAt: row.dead_lettered_at, nextAttemptAt: row.next_attempt_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapBindingThreadAlias(row: BindingThreadAliasRow): BindingThreadAlias { return { id: row.id, publicationKey: row.publication_key, bindingId: row.binding_id, bindingGeneration: Number(row.binding_generation), chatId: row.chat_id, paneId: row.pane_id, sourceMainMessageId: row.source_main_message_id, actionMessageId: row.action_message_id, topicId: row.topic_id, rootMessageId: row.root_message_id, state: row.state as BindingThreadAlias["state"], createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapWorkerSessionThread(row: WorkerSessionThreadRow): WorkerSessionThread { return { id: row.id, publicationKey: row.publication_key, workerId: row.worker_id, workerSessionGeneration: Number(row.worker_session_generation), parentBindingId: row.parent_binding_id, parentBindingGeneration: Number(row.parent_binding_generation), parentPaneId: row.parent_pane_id, chatId: row.chat_id, mode: row.mode as WorkerSessionThread["mode"], sourceMainMessageId: row.source_main_message_id, actionMessageId: row.action_message_id, topicId: row.topic_id, rootMessageId: row.root_message_id, state: row.state as WorkerSessionThread["state"], createdAt: row.created_at, activatedAt: row.activated_at, staleAt: row.stale_at, updatedAt: row.updated_at }; }
export function mapAnswerPage(row: AnswerPageRow): AnswerPage { return { promptId: row.prompt_id, pageIndex: Number(row.page_index), messageId: row.message_id, cardId: row.card_id, elementId: row.element_id, sourceStart: Number(row.source_start), sequence: Number(row.sequence), state: row.state as AnswerPageState, deliveryMode: (row.delivery_mode ?? "streaming") as AnswerPageDeliveryMode, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapProjectSelection(row: ProjectSelectionRow): ProjectSelection { return { id: row.id, commandMessageId: row.command_message_id, selectorMessageId: row.selector_message_id, chatId: row.chat_id, topicId: row.topic_id, rootMessageId: row.root_message_id, actorOpenId: row.actor_open_id, requestedTitle: row.requested_title, initialPromptText: row.initial_prompt_text ?? null, agentKind: (row.agent_kind ?? "traex") as AgentKind, selectedProjectId: row.selected_project_id, bindingId: row.binding_id, state: row.state as ProjectSelectionState, error: row.error, expiresAt: row.expires_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
