import type {
  AgentState, AnswerPage, AnswerPageState, Binding, BindingState, CardInteraction, CardInteractionActionKind, CardInteractionState, DeliveryFailureClass, InstanceLease,
  OutboundReply, OutboundReplyKind, OutboundReplyState, OutboundTargetRole, PaneControlOperation,
  PaneControlOperationKind, PaneControlOperationState, ProjectSelection, ProjectSelectionState,
  PromptDispatchKind, PromptJob, PromptObservationState, PromptState, RequestCardRole, SteeringOrigin,
  RetiredPaneCleanupOperation, RetiredPaneCleanupState
} from "../domain/types.js";
import type { AttachmentState, ProvisioningCheckpoint, SessionLifecycle } from "../domain/pane-thread-lifecycle.js";

export type SqlValue = string | number | bigint | null;
export type BindingRow = Record<string, SqlValue> & {
  id: string; creator_open_id: string | null; project_id: string | null; workspace_id: string; chat_id: string; topic_id: string | null; root_message_id: string | null;
  retired_topic_id: string | null; retired_root_message_id: string | null; replaces_binding_id: string | null; reserved_topic_id: string | null;
  reserved_root_message_id: string | null; reset_message_id: string | null; pane_id: string | null; traex_session_id: string | null;
  agent_session_source: string | null; agent_session_agent: string | null; agent_session_kind: string | null; agent_session_value: string | null;
  title: string; runtime: string; state: string; status_message_id: string | null; last_agent_state: string; last_output_fingerprint: string | null;
  lifecycle: string; attachment: string; generation: number; provisioning_checkpoint: string; degradation_count: number; has_completed_turn: number;
  last_observed_at: string | null; archived_at: string | null; last_activity_at: string; created_at: string; updated_at: string;
};
export type PromptRow = Record<string, SqlValue> & { id: string; binding_id: string; lark_message_id: string; actor_open_id: string; body: string; execution_origin: string; state: string; dispatch_kind: string; parent_prompt_id: string | null; steering_origin: string | null; source_prompt_id: string | null; was_detached: number; dispatched_at: string | null; transcript_turn_id: string | null; transcript_turn_started_at: string | null; observation_state: string; attempt_count: number; error: string | null; created_at: string; updated_at: string; };
export type OutboundReplyRow = Record<string, SqlValue> & { id: string; idempotency_key: string; binding_id: string | null; prompt_id: string | null; view_version: number | null; selection_id: string | null; card_role: string | null; target_role: string | null; root_message_id: string; kind: string; payload: string; state: string; attempt_count: number; error: string | null; delivered_message_id: string | null; next_attempt_at: string; created_at: string; updated_at: string; card_id_checkpoint: string | null; delivery_order: number; lane_key: string; failure_class: string | null; http_status: number | null; lark_error_code: string | null; auto_recovery_count: number; dead_lettered_at: string | null; };
export type AnswerPageRow = Record<string, SqlValue> & { prompt_id: string; page_index: number; message_id: string | null; card_id: string | null; element_id: string; source_start: number; sequence: number; state: string; created_at: string; updated_at: string; };
export type ProjectSelectionRow = Record<string, SqlValue> & { id: string; command_message_id: string; selector_message_id: string | null; chat_id: string; topic_id: string | null; root_message_id: string; actor_open_id: string; requested_title: string | null; initial_prompt_text: string | null; selected_project_id: string | null; binding_id: string | null; state: string; error: string | null; expires_at: string; created_at: string; updated_at: string; };
export type RetiredPaneCleanupRow = Record<string, SqlValue> & { id: string; old_binding_id: string; replacement_binding_id: string; pane_id: string; expected_workspace_id: string; expected_project_id: string; expected_cwd: string; expected_terminal_id: string; actor_open_id: string; state: string; attempt_count: number; detail: string | null; created_at: string; updated_at: string; };
export type PaneControlOperationRow = Record<string, SqlValue> & { id: string; idempotency_key: string; binding_id: string; pane_id: string; terminal_id: string | null; binding_generation: number; kind: string; payload: string | null; parent_prompt_id: string | null; state: string; attempt_count: number; detail: string | null; actor_open_id: string; source_message_id: string; created_at: string; updated_at: string; };
export type CardInteractionRow = Record<string, SqlValue> & { id: string; binding_id: string; binding_generation: number; actor_open_id: string; action_kind: string; parent_prompt_id: string | null; target_prompt_id: string | null; state: string; expires_at: string; result_code: string | null; created_at: string; claimed_at: string | null; consumed_at: string | null; };

export function mapInstanceLease(row: { owner_id: string; fencing_token: number; expires_at: string; updated_at: string }): InstanceLease { return { ownerId: row.owner_id, fencingToken: Number(row.fencing_token), expiresAt: row.expires_at, updatedAt: row.updated_at }; }
export function mapPaneControlOperation(row: PaneControlOperationRow): PaneControlOperation { return { id: row.id, idempotencyKey: row.idempotency_key, bindingId: row.binding_id, paneId: row.pane_id, terminalId: row.terminal_id, bindingGeneration: Number(row.binding_generation), kind: row.kind as PaneControlOperationKind, payload: row.payload, parentPromptId: row.parent_prompt_id, state: row.state as PaneControlOperationState, attemptCount: Number(row.attempt_count), detail: row.detail, actorOpenId: row.actor_open_id, sourceMessageId: row.source_message_id, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapBinding(row: BindingRow): Binding { return { id: row.id, creatorOpenId: row.creator_open_id ?? null, projectId: row.project_id, workspaceId: row.workspace_id, chatId: row.chat_id, topicId: row.topic_id, rootMessageId: row.root_message_id, retiredTopicId: row.retired_topic_id ?? null, retiredRootMessageId: row.retired_root_message_id ?? null, replacesBindingId: row.replaces_binding_id ?? null, reservedTopicId: row.reserved_topic_id ?? null, reservedRootMessageId: row.reserved_root_message_id ?? null, resetMessageId: row.reset_message_id ?? null, paneId: row.pane_id, traexSessionId: row.traex_session_id, agentSessionSource: row.agent_session_source ?? null, agentSessionAgent: row.agent_session_agent ?? null, agentSessionKind: row.agent_session_kind as "id" | "path" | null, agentSessionValue: row.agent_session_value ?? null, title: row.title, runtime: "traex", state: row.state as BindingState, statusMessageId: row.status_message_id, lastAgentState: row.last_agent_state as AgentState, lastOutputFingerprint: row.last_output_fingerprint, lifecycle: row.lifecycle as SessionLifecycle, attachment: row.attachment as AttachmentState, generation: Number(row.generation), provisioningCheckpoint: row.provisioning_checkpoint as ProvisioningCheckpoint, degradationCount: Number(row.degradation_count), hasCompletedTurn: Boolean(row.has_completed_turn), lastObservedAt: row.last_observed_at, archivedAt: row.archived_at, lastActivityAt: row.last_activity_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapCardInteraction(row: CardInteractionRow): CardInteraction { return { id: row.id, bindingId: row.binding_id, bindingGeneration: Number(row.binding_generation), actorOpenId: row.actor_open_id, actionKind: row.action_kind as CardInteractionActionKind, parentPromptId: row.parent_prompt_id, targetPromptId: row.target_prompt_id, state: row.state as CardInteractionState, expiresAt: row.expires_at, resultCode: row.result_code, createdAt: row.created_at, claimedAt: row.claimed_at, consumedAt: row.consumed_at }; }
export function mapRetiredPaneCleanup(row: RetiredPaneCleanupRow): RetiredPaneCleanupOperation { return { id: row.id, oldBindingId: row.old_binding_id, replacementBindingId: row.replacement_binding_id, paneId: row.pane_id, expectedWorkspaceId: row.expected_workspace_id, expectedProjectId: row.expected_project_id, expectedCwd: row.expected_cwd, expectedTerminalId: row.expected_terminal_id, actorOpenId: row.actor_open_id, state: row.state as RetiredPaneCleanupState, attemptCount: Number(row.attempt_count), detail: row.detail, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapPrompt(row: PromptRow): PromptJob { return { id: row.id, bindingId: row.binding_id, larkMessageId: row.lark_message_id, actorOpenId: row.actor_open_id, body: row.body, executionOrigin: row.execution_origin as PromptJob["executionOrigin"], dispatchKind: row.dispatch_kind as PromptDispatchKind, parentPromptId: row.parent_prompt_id, steeringOrigin: row.steering_origin as SteeringOrigin | null, sourcePromptId: row.source_prompt_id, wasDetached: Boolean(row.was_detached), dispatchedAt: row.dispatched_at, transcriptTurnId: row.transcript_turn_id, transcriptTurnStartedAt: row.transcript_turn_started_at, observationState: row.observation_state as PromptObservationState, state: row.state as PromptState, attemptCount: Number(row.attempt_count), error: row.error, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapOutboundReply(row: OutboundReplyRow): OutboundReply { return { id: row.id, idempotencyKey: row.idempotency_key, bindingId: row.binding_id, rootMessageId: row.root_message_id, promptId: row.prompt_id, viewVersion: row.view_version === null ? null : Number(row.view_version), selectionId: row.selection_id, cardRole: row.card_role as RequestCardRole | null, targetRole: row.target_role as OutboundTargetRole | null, kind: row.kind as OutboundReplyKind, payload: row.payload, state: row.state as OutboundReplyState, attemptCount: Number(row.attempt_count), error: row.error, deliveredMessageId: row.delivered_message_id, cardIdCheckpoint: row.card_id_checkpoint ?? null, failureClass: row.failure_class as DeliveryFailureClass | null, httpStatus: row.http_status === null ? null : Number(row.http_status), larkErrorCode: row.lark_error_code, autoRecoveryCount: Number(row.auto_recovery_count ?? 0), deadLetteredAt: row.dead_lettered_at, nextAttemptAt: row.next_attempt_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapAnswerPage(row: AnswerPageRow): AnswerPage { return { promptId: row.prompt_id, pageIndex: Number(row.page_index), messageId: row.message_id, cardId: row.card_id, elementId: row.element_id, sourceStart: Number(row.source_start), sequence: Number(row.sequence), state: row.state as AnswerPageState, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapProjectSelection(row: ProjectSelectionRow): ProjectSelection { return { id: row.id, commandMessageId: row.command_message_id, selectorMessageId: row.selector_message_id, chatId: row.chat_id, topicId: row.topic_id, rootMessageId: row.root_message_id, actorOpenId: row.actor_open_id, requestedTitle: row.requested_title, initialPromptText: row.initial_prompt_text ?? null, selectedProjectId: row.selected_project_id, bindingId: row.binding_id, state: row.state as ProjectSelectionState, error: row.error, expiresAt: row.expires_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
