import { createConnection } from "node:net";
import { createInterface } from "node:readline";
type Request = { jsonrpc: "2.0"; id?: string | number; method: string; params?: Record<string, unknown> };
const scopedArguments = { requestId: str(), capability: { type: "string", minLength: 32, maxLength: 256 } };
const commandKinds = ["stop", "steer", "model", "reset", "new", "projects", "spaces", "panes", "sessions", "failures", "status", "attach", "rename", "close", "pane_close_request", "pane_close_confirm", "reattach", "replace", "resume", "awake", "skip", "worker_create", "help"];
const instanceKinds = ["projects", "project", "instances", "instance", "to", "steer_instance", "stop_instance"];
const interpretationResultSchema = { oneOf: [
  { type: "object", properties: { outcome: { const: "command" }, source: { const: "controller" }, family: { const: "swarm" }, command: { type: "object", properties: { kind: { enum: commandKinds } }, required: ["kind"] } }, required: ["outcome", "source", "family", "command"] },
  { type: "object", properties: { outcome: { const: "command" }, source: { const: "controller" }, family: { const: "instance" }, command: { type: "object", properties: { kind: { enum: instanceKinds } }, required: ["kind"] } }, required: ["outcome", "source", "family", "command"] },
  { type: "object", properties: { outcome: { const: "task" }, source: { const: "controller" } }, required: ["outcome", "source"] },
  { type: "object", properties: { outcome: { enum: ["clarification", "unsupported"] }, message: str(), examples: { type: "array", maxItems: 3, items: str() } }, required: ["outcome", "message", "examples"] }
] };
const tools = [
  { name: "get_interpretation_context", description: "Read the bounded user request, configured project catalog, and current thread scope for this request. Use this before interpreting; it is read-only and cannot execute a Swarm action.", inputSchema: schema(scopedArguments) },
  { name: "inspect_swarm_target", description: "Resolve an exact configured project or Agent name when the request names a target. Use this only to remove target ambiguity; it is read-only and returns no terminal content.", inputSchema: schema({ ...scopedArguments, name: { ...str(), description: "Exact project ID, display name, space name, Worker ID, or Worker name from the user request." } }) },
  { name: "submit_interpretation", description: "Submit exactly one schema-validated command, task, clarification, or unsupported proposal for this request. This records an interpretation only; it never executes the requested operation, and a mutation still requires human confirmation.", inputSchema: schema({ ...scopedArguments, result: interpretationResultSchema }) }
];
const methods: Record<string, string> = { get_interpretation_context: "getInterpretationContext", inspect_swarm_target: "inspectSwarmTarget", submit_interpretation: "submitInterpretation" };
export async function handleControllerMcpRequest(request: Request, invoke: (tool: string, args: Record<string, unknown>) => Promise<unknown>): Promise<object | null> { if (request.method === "notifications/initialized") return null; if (request.method === "initialize") return ok(request.id, { protocolVersion: "2025-03-26", capabilities: { tools: {} }, serverInfo: { name: "herdr-swarm-controller", version: "1.0.0" } }); if (request.method === "tools/list") return ok(request.id, { tools }); if (request.method !== "tools/call") return fail(request.id, -32601, "Method not found"); const name = String(request.params?.name ?? ""); const method = methods[name]; if (!method) return fail(request.id, -32602, "Unknown tool"); const args = object(request.params?.arguments); const requestId = typeof args.requestId === "string" ? args.requestId : ""; const capability = typeof args.capability === "string" ? args.capability : ""; if (!requestId || capability.length < 32 || capability.length > 256) return fail(request.id, -32602, "Missing or invalid request scope"); const { requestId: _requestId, capability: _capability, ...rest } = args; try { const value = await invoke(method, { requestId, capability, ...rest }); return ok(request.id, { content: [{ type: "text", text: JSON.stringify(value) }], structuredContent: value }); } catch (error) { return ok(request.id, { isError: true, content: [{ type: "text", text: error instanceof Error ? error.message : String(error) }] }); } }
async function call(socketPath: string, request: Record<string, unknown>): Promise<unknown> { return new Promise((resolve, reject) => { const socket = createConnection(socketPath); const chunks: Buffer[] = []; socket.once("connect", () => socket.write(`${JSON.stringify(request)}\n`)); socket.on("data", (chunk) => chunks.push(chunk)); socket.once("error", reject); socket.once("end", () => { const response = JSON.parse(Buffer.concat(chunks).toString()) as { ok: boolean; result?: unknown; error?: string }; response.ok ? resolve(response.result) : reject(new Error(response.error)); }); }); }
async function main() { const socket = process.argv[process.argv.indexOf("--socket") + 1]; if (!socket) throw new Error("Missing --socket"); for await (const line of createInterface({ input: process.stdin })) { const request = JSON.parse(line) as Request; const response = await handleControllerMcpRequest(request, (tool, args) => call(socket, { jobId: args.requestId, capability: args.capability, tool, arguments: args })); if (response) process.stdout.write(`${JSON.stringify(response)}\n`); } }
function str() { return { type: "string", minLength: 1 }; } function schema(properties: Record<string, unknown>) { return { type: "object", properties, required: Object.keys(properties), additionalProperties: false }; } function object(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; } function ok(id: unknown, result: unknown) { return { jsonrpc: "2.0", id: id ?? null, result }; } function fail(id: unknown, code: number, message: string) { return { jsonrpc: "2.0", id: id ?? null, error: { code, message } }; }
if (import.meta.url === `file://${process.argv[1]}`) void main().catch((error) => { process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`); process.exitCode = 1; });
