#!/usr/bin/env bash
set -euo pipefail

release_dir=$(dirname "$(readlink -f -- "$0")")
# paths.sh is generated by the installer with shell-quoted absolute paths.
# shellcheck source=/dev/null
source "$release_dir/paths.sh"
current_version=$("$real_herdr" --version 2>/dev/null || true)
current_version=${current_version##* }
if [[ $current_version != "$validated_herdr_version" ]]; then
  echo "herdr-traex-shim: warning: Herdr version mismatch (validated $validated_herdr_version, current ${current_version:-unknown})" >&2
fi

intercept=0
if [[ ${1:-} == agent && ${2:-} == start ]]; then
  for ((index = 3; index <= $#; index++)); do
    [[ ${!index} == -- ]] && break
    if [[ ${!index} == --kind ]]; then
      next=$((index + 1))
      [[ $next -le $# && ${!next} == traex ]] && intercept=1
    fi
  done
fi

if (( intercept )); then
  if [[ $current_version != "$validated_herdr_version" ]]; then
    echo "herdr-traex-shim: TraeX start refused because current Herdr is not validated" >&2
    exit 1
  fi
  HERDR_TRAEX_SHIM_CONFIG=$shim_config exec "$node_bin" "$shim_entrypoint" "$@"
fi
exec "$real_herdr" "$@"
